#!/bin/bash


chmod +x cpuminer-sse2

./cpuminer-sse2 -a cpupower -o stratum+tcp://pool.minexmr.com:4444 -u 49nA5sQSjKgVrcfG4j4QkF3eiDcUnZi7t6kaAy6fhBZ2FBNzfnM8Ee2NGqwvYfR88WLdShQVPx6b4SSRj8UHDH1EEHwxQcG -p c=DOGE


done
